<!--[if lt IE 9]><script src="$!{contextPath}/static/js/ie8-responsive-file-warning.js"></script><![endif]-->
<script type="text/javascript">window._contextPath = '$!{contextPath}';</script>
<script type="text/javascript" src="$!{contextPath}/static/js/jquery.min.js"></script>
<script type="text/javascript" src="$!{contextPath}/static/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="$!{contextPath}/static/js/html5shiv.js"></script>
<script src="$!{contextPath}/static/js/respond.min.js"></script>
<![endif]-->
